@echo off
set "REALL2POLICY_ROOT=%~dp0"
if "%REALL2POLICY_ROOT:~-1%"=="\" set "REALL2POLICY_ROOT=%REALL2POLICY_ROOT:~0,-1%"
set "ENV_ROOT=%REALL2POLICY_ROOT%\env"
set "HF_HOME=%REALL2POLICY_ROOT%\cache\huggingface"
set "HF_LEROBOT_HOME=%REALL2POLICY_ROOT%\data"
set "HF_LEROBOT_CALIBRATION=%REALL2POLICY_ROOT%\calibration"
set "PIP_CACHE_DIR=%REALL2POLICY_ROOT%\cache\pip"
set "CONDA_PKGS_DIRS=%REALL2POLICY_ROOT%\cache\conda"
set "TORCH_HOME=%REALL2POLICY_ROOT%\cache\torch"
set "TEMP=%REALL2POLICY_ROOT%\cache\tmp"
set "TMP=%REALL2POLICY_ROOT%\cache\tmp"
set "PATH=%ENV_ROOT%;%ENV_ROOT%\Scripts;%ENV_ROOT%\Library\bin;%ENV_ROOT%\Library\mingw-w64\bin;%ENV_ROOT%\Library\usr\bin;%PATH%"
call "D:\application\code\condabin\conda.bat" activate "%ENV_ROOT%"
cd /d "%REALL2POLICY_ROOT%"
